apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-app
  labels:
    app: argo_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo_app
  template:
    metadata:
      labels:
        app: argo_app
    spec:
      containers:
      - name: php-apache-spesys-1-2
        image: kmaster:31320/php_apache_spesys:1.2
        ports:
        - containerPort: 80


   